trigger:
  branches:
    include: [master, develop, "release-*" ]
  paths:
    exclude: ["*.md", .gitignore]
  tags:
    include: ["v*"]

# PR always trigger build

# add nf-tools repo to resources (for Azure Pipelines templates)
resources:
  repositories:
    - repository: templates
      type: github
      name: nanoframework/nf-tools
      endpoint: nfbot

pool:
  vmImage: 'VS2017-Win2016'

variables:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  nugetPackageName: 'nanoFramework.Windows.Networking.Sockets'
  repoName: 'lib-Windows.Networking.Sockets'

steps:

# step from template @ nf-tools repo
# all build, update and publish steps
- template: azure-pipelines-templates/class-lib-build.yml@templates  
  parameters:
    sourceFileName: 'win_net_sockets_native.cpp'
    classLibName: 'Windows.Networking.Sockets'

# update dependencies
- task: UpdatenFDependencies@1
  inputs:
    gitHubToken: $(GitHubToken)
    repositoriesToUpdate: |
      lib-nanoFramework.Hardware.Esp32
  condition: and( succeeded(), startsWith(variables['Build.SourceBranch'], 'refs/tags/v') )
  displayName: Update dependent class libs

# step from template @ nf-tools repo
# report error
- template: azure-pipelines-templates/discord-webhook-task.yml@templates  
  parameters:
    status: 'failure'
    webhookUrl: '$(DiscordWebhook)'
    message: ''
